"""JobOffer Fonctionnel

Revision ID: 5a520064c8d5
Revises: 
Create Date: 2024-03-18 15:22:47.445625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a520064c8d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('dateEntryOffice', sa.Date(), nullable=False),
    sa.Column('deadlineApply', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hoursPerWeek', sa.Float(), nullable=False),
    sa.Column('compliantEmployer', sa.Boolean(), nullable=False),
    sa.Column('internship', sa.Boolean(), nullable=False),
    sa.Column('offerStatus', sa.Integer(), nullable=False),
    sa.Column('offerLink', sa.String(length=255), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('employerId', sa.Integer(), nullable=False),
    sa.Column('scheduleId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('isModerator', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('job_offer')
    # ### end Alembic commands ###
