"""JobOffer Fonctionnel

Revision ID: e44bb5fff8f7
Revises: bda06c9f7a4d
Create Date: 2024-03-18 13:57:23.386338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e44bb5fff8f7'
down_revision = 'bda06c9f7a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employerId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('scheduleId', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('dateEntryOffice',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('deadlineApply',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('hoursPerWeek',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('compliantEmployer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('internship',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('offerStatus',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('offerLink',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('urgent',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.drop_column('ScheduleId')
        batch_op.drop_column('EmployerId')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isModerator', sa.Boolean(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('isModerator')
        batch_op.drop_column('active')

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EmployerId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ScheduleId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('urgent',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('offerLink',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('offerStatus',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('internship',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('compliantEmployer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('hoursPerWeek',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('deadlineApply',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('dateEntryOffice',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('scheduleId')
        batch_op.drop_column('employerId')

    # ### end Alembic commands ###
