name: PROD - Build & Deploy
on:
  push:
    branches: [PROD]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2

        with:
          host: ${{secrets.PROD_SSH_HOST}}
          key: ${{secrets.PROD_SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME}}

          script: |
            sudo systemctl stop front-end
            sudo systemctl stop back-end
            rm -r prod_project
            mkdir prod_project
            cd dev_project
            git clone -b PROD https://github.com/ecoleduweb/ProjetApplicationH2024.git
            echo 'Deployment successful to PROD server'
            echo 'Installing backend packages'
            sudo apt-get update -y
            sudo apt-get install -y libmariadb-dev
            python -m pip install --upgrade pip
            cd /${{ secrets.SSH_USERNAME}}/prod_project/ProjetApplicationH2024/back-end/
            pip install -r requirements.txt
            cd /${{ secrets.SSH_USERNAME}}/prod_project/ProjetApplicationH2024/back-end/API
            touch .env
            echo DATABASE_TEST_URL=${{ secrets.DATABASE_TEST_URL }} >> .env
            echo DATABASE_DEV_URL=${{ secrets.DATABASE_DEV_URL }} >> .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo 'Installing packages'
            sudo systemctl enable back-end
            sudo systemctl start back-end
            cd /${{ secrets.SSH_USERNAME}}/prod_project/ProjetApplicationH2024/front-end/projet_application
            npm i
            touch .env
            echo PUBLIC_BASE_URL = ${{ secrets.FRONT_PUBLIC_URL }} >> .env
            echo HOST = ${{ secrets.FRONT_HOST }} >> .env
            echo 'Starting services'
            sudo systemctl enable front-end
            sudo systemctl start front-end
